### ISSUE TITLE
Editing conversation - Save conversation error

### ISSUE THREAD

**Issue by rahul101001000** [go-donew/mentoring-platform#3]
### Description

![image](https://user-images.githubusercontent.com/63799217/173017669-ddcfbf93-af31-4087-8469-518b8eedcfb0.png)

An unexpected error occurred. Please try again in a few seconds or report this issue.

**Comment by gamemaker1** [comment]
This usually happens due to a drop in internet connectivity or when a deployment is taking place. I had deployed a new version approximately an hour ago, which might have caused this issue.
